### ISSUE TITLE
Database folder isn't always so

### ISSUE THREAD

**Issue by chew-z** [AaronVanGeffen/ExportPhotosLibrary#1]
Hello,

I have been testing your script. It seems like you cannot take folder structure of Photos Library.photoslibrary/Database for granted. 

In my case it looks like this:

```
ls '/Volumes/Elements/Pictures/Photos Library.photoslibrary/database'                                                      (env: Flickr3)
DataModelVersion.plist  Library.apdb      Person.db-wal        RKAlbum_name.skindex               metaSchema.db-wal
ImageProxies.apdb       Library.apdb-wal  Properties.apdb      RKVersion_searchIndexText.skindex  metaSchema.db.lock
ImageProxies.apdb-wal   Person.db         Properties.apdb-wal  metaSchema.db
```

So I have encountered two problems:
1. folder name is 'database' not 'Database'
2. Person.db and Properties.apdb is not inside /apdb folder

That was easy fix for me but maybe there could be more general solution?

**Comment by AaronVanGeffen** [comment]
Interesting! Thank you for the bug report. I'll see if I can reproduce this with a clean photo library later.

Using Person.db and Properties.apdb from the database folder rather than apdb shouldn't be a problem, either way, actually — they seem to exist as symlinks there for me, too.

**Comment by chew-z** [comment]
As a sidenote I have also had script crashing in photoTimestamp(row) as for one picture in my library row["offset"] were None. 

But overall this code helped me enormously in syncing Photos with Flickr. Thanks.

**Comment by AaronVanGeffen** [comment]
Thank you again for the kind words. I've addressed your concerns in 2db277d06a87af5138be0e4086a584df90e672f7 and 0ab30271379184e7f82ba78d8b052e2ecd6d545e.

I'm unable to reproduce the offset error, though. Is the anything of note about the image that triggers it?

**Comment by chew-z** [comment]
Nah, that was some odd picture probably. I had been adding images to Photos via various means.
But it seems row["offset"] == None is not impossible so a check might be in order.

I have just added:

```
def photoTimestamp(row):
    if row["offset"] is not None:
        return datetime.fromtimestamp(epoch + row["date"] + row["offset"], timezone.utc)
    else:
        return datetime.fromtimestamp(epoch + row["date"], timezone.utc)
```

**Comment by AaronVanGeffen** [comment]
Sorry for the late reply — I forgot to address this. I hope to have covered your case with a3cc9f1, in a series of commits to address macOS Sierra compatibility.

Thank you again for your report. I hope you'll continue to use the script on Sierra, too.
